--Lab 5
--2.2
EXEC ELEARN_APP_ADMIN.PROC_DYNAM('SELECT * FROM ELEARN_APP_ADMIN.SOLVES');
EXEC ELEARN_APP_ADMIN.PROC_DYNAM('DECLARE v_id NUMBER(4); BEGIN DELETE FROM ELEARN_APP_ADMIN.SOLVES;COMMIT; SELECT student_id INTO v_id FROM ELEARN_APP_ADMIN.SOLVES WHERE STUDENT_ID=1 AND HOMEWORK_ID=2; END; ');

select * from elearn_app_admin.solves;

select * from session_privs;
select * from user_tab_privs;

delete from elearn_app_admin.solves;

--after adding authid current_user:
EXEC ELEARN_APP_ADMIN.PROC_DYNAM('SELECT * FROM ELEARN_APP_ADMIN.SOLVES');
EXEC ELEARN_APP_ADMIN.PROC_DYNAM('DECLARE v_id NUMBER(4); BEGIN DELETE FROM ELEARN_APP_ADMIN.SOLVES;COMMIT; SELECT student_id INTO v_id FROM ELEARN_APP_ADMIN.SOLVES WHERE STUDENT_ID=1 AND HOMEWORK_ID=2; END; ');

--after using regexp_like:
EXEC ELEARN_APP_ADMIN.PROC_DYNAM('SELECT * FROM ELEARN_APP_ADMIN.SOLVES');
EXEC ELEARN_APP_ADMIN.PROC_DYNAM('DECLARE v_id NUMBER(4); BEGIN DELETE FROM ELEARN_APP_ADMIN.SOLVES;COMMIT; SELECT student_id INTO v_id FROM ELEARN_APP_ADMIN.SOLVES WHERE STUDENT_ID=1 AND HOMEWORK_ID=2; END; ');

--3
EXEC elearn_app_admin.VERIFY_LOGIN('ELEARN_STUDENT2','Password1');
EXEC elearn_app_admin.VERIFY_LOGIN('ELEARN_STUDENT2','Password2');

EXEC elearn_app_admin.VERIFY_LOGIN('ELEARN_STUDENT2''--','Password2');
EXEC elearn_app_admin.VERIFY_LOGIN('ABRACADABRA99'' OR 1=1 --','HOCUS-POCUS');

--option1
--ACCEPT USERNAME PROMPT 'USER NAME:' 
--ACCEPT PASSWORD PROMPT 'PASSWORD:'
--EXEC elearn_app_admin.VERIFY_LOGIN_SAFE ('&USERNAME','&PASSWORD');

EXEC elearn_app_admin.VERIFY_LOGIN_SAFE('ELEARN_STUDENT2','Password1');
EXEC elearn_app_admin.VERIFY_LOGIN_SAFE('ELEARN_STUDENT2','Password2');

EXEC elearn_app_admin.VERIFY_LOGIN_SAFE('ELEARN_STUDENT2''--','Password2');
EXEC elearn_app_admin.VERIFY_LOGIN_SAFE('ABRACADABRA99'' OR 1=1 --','HOCUS-POCUS');

--option 2
EXEC elearn_app_admin.VERIFY_LOGIN_SAFE2('ELEARN_STUDENT2','Password1');
EXEC elearn_app_admin.VERIFY_LOGIN_SAFE2('ELEARN_STUDENT2','Password2');

EXEC elearn_app_admin.VERIFY_LOGIN_SAFE2('ELEARN_STUDENT2''--','Password2');
EXEC elearn_app_admin.VERIFY_LOGIN_SAFE2('ABRACADABRA99'' OR 1=1 --','HOCUS-POCUS');